// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8dHgcEtPJbOMUwZePE6gM_RAXCNHCNM',
    appId: '1:1079703493903:web:b57548aa9940b97580727a',
    messagingSenderId: '1079703493903',
    projectId: 'fb-auth-riverpod-cf4e0',
    authDomain: 'fb-auth-riverpod-cf4e0.firebaseapp.com',
    storageBucket: 'fb-auth-riverpod-cf4e0.appspot.com',
    measurementId: 'G-04X51QG49G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu8T0HiKbGqClvJsXNSXXbnIIFfmwS0AQ',
    appId: '1:1079703493903:android:7e24c3edd689cd4d80727a',
    messagingSenderId: '1079703493903',
    projectId: 'fb-auth-riverpod-cf4e0',
    storageBucket: 'fb-auth-riverpod-cf4e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5US5Ek3KSHdp9VrCuYTy3-UL3K0BlwFc',
    appId: '1:1079703493903:ios:328ab4ba38b5770480727a',
    messagingSenderId: '1079703493903',
    projectId: 'fb-auth-riverpod-cf4e0',
    storageBucket: 'fb-auth-riverpod-cf4e0.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

}